[versions]
# Tooling / plugins
shadow = "8.1.1"
launch4j = "4.0.0"

# Runtime dependencies
swt = "3.129.0"
xstream = "1.4.21"
commonsCodec = "1.17.0"
okhttp = "4.12.0"

# Test dependencies
junit4 = "4.13.2"

[libraries]
swtWin64 = { module = "org.eclipse.platform:org.eclipse.swt.win32.win32.x86_64", version.ref = "swt" }
xstream = { module = "com.thoughtworks.xstream:xstream", version.ref = "xstream" }
commonsCodec = { module = "commons-codec:commons-codec", version.ref = "commonsCodec" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
junit4 = { module = "junit:junit", version.ref = "junit4" }

[plugins]
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
launch4j = { id = "edu.sc.seis.launch4j", version.ref = "launch4j" }
