[versions]
# Tooling / plugins
shadow = "9.3.1"
launch4j = "4.0.0"

# Runtime dependencies
swt = "3.132.0"
xstream = "1.4.21"
okhttp = "5.3.2"

# Test dependencies
junit5 = "5.14.2"

[libraries]
swtWin64 = { module = "org.eclipse.platform:org.eclipse.swt.win32.win32.x86_64", version.ref = "swt" }
xstream = { module = "com.thoughtworks.xstream:xstream", version.ref = "xstream" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
junit5Jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit5" }

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
launch4j = { id = "edu.sc.seis.launch4j", version.ref = "launch4j" }
